[sdl]
fullscreen=false
autolock=true

[dosbox]
memsize=32
machine=svga_s3

[cpu]
core=auto
cputype=pentium
cycles=3000

[mixer]
nosound=false
rate=44100
blocksize=1024

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[speaker]
pcspeaker=true

[autoexec]
mount c .
mount l .
c:
cd XCOM3
xcomapoc.exe
