[sdl]
fullscreen=false
autolock=true

[dosbox]
memsize=128
machine=svga_s3
xms=true
ems=true
umb=true

[cpu]
core=auto
cputype=pentium
cycles=max

[mixer]
nosound=false
rate=44100
blocksize=1024

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[speaker]
pcspeaker=true

[autoexec]
mount c .
c:
cd XCOM3
xcomapoc.exe
